# tests/test_cases_comprehensive.py
"""
Comprehensive test cases for debt collection chatbot workflows.
30 Hinglish test cases per workflow: already paid, dispute, callback, unable to pay, willing, unknown
Total: 180 test cases (all in Hinglish)
"""

# Test cases organized by workflow - All in Hinglish
TEST_CASES = {
    "already_paid": [
        "Main ne pehle hi payment kar diya hai",
        "Payment ho gaya hai last week",
        "Main ne transfer kar diya amount",
        "Dues clear ho gaye hain",
        "Main ne already pay kar diya",
        "Maine payment kar di thi pichle mahine",
        "Amount transfer ho chuka hai",
        "Main ne sab paise de diye hain",
        "Payment complete ho gaya hai",
        "Maine loan clear kar diya hai",
        "Main ne pehle hi settle kar diya",
        "Payment receipt bhej di hai",
        "Maine UPI se transfer kar diya",
        "Bank se payment ho gaya hai",
        "Maine cheque bhej diya hai",
        "Online payment kar diya maine",
        "Maine full amount pay kar diya",
        "Payment done hai last month",
        "Maine EMI pay kar di thi",
        "Account clear ho gaya hai mera",
        "Maine payment proof bhej diya",
        "Transaction complete ho gaya",
        "Maine sab dues clear kar diye",
        "Payment successful ho gaya",
        "Maine loan amount pay kar diya",
        "Mera payment process ho gaya",
        "Maine payment confirm kar diya",
        "Amount deduct ho gaya hai",
        "Maine payment kar di thi kal",
        "Payment receipt mil gaya hai"
    ],
    
    "dispute": [
        "Yeh loan mera nahi hai",
        "Maine yeh loan kabhi nahi liya",
        "Yeh galat hai, mujhe kuch nahi dena",
        "Yeh fraud lagta hai",
        "Yeh mera account nahi hai",
        "Maine yeh loan apply nahi kiya",
        "Yeh meri loan nahi hai",
        "Maine kabhi yeh loan nahi liya",
        "Yeh mistake hai",
        "Yeh wrong person hai",
        "Maine yeh debt nahi liya",
        "Yeh unauthorized transaction hai",
        "Maine yeh loan sign nahi kiya",
        "Yeh identity theft lagta hai",
        "Maine yeh loan approve nahi kiya",
        "Yeh meri responsibility nahi hai",
        "Maine yeh loan accept nahi kiya",
        "Yeh error hai system mein",
        "Maine yeh loan acknowledge nahi kiya",
        "Yeh meri liability nahi hai",
        "Maine yeh loan authorize nahi kiya",
        "Yeh fake loan hai",
        "Maine yeh loan verify nahi kiya",
        "Yeh meri mistake nahi hai",
        "Maine yeh loan process nahi kiya",
        "Yeh wrong account hai",
        "Maine yeh loan document nahi sign kiya",
        "Yeh meri fault nahi hai",
        "Maine yeh loan agree nahi kiya",
        "Yeh incorrect information hai"
    ],
    
    "callback": [
        "Aap baad mein call kar sakte hain?",
        "Main abhi busy hoon, kal call karo",
        "Abhi available nahi hoon, next week call karo",
        "Main out of town hoon, next month call karo",
        "Abhi baat nahi kar sakta, baad mein call karo",
        "Kal call karo please",
        "Main abhi office mein hoon, baad mein call karo",
        "Next week call kar lena",
        "Abhi time nahi hai, evening mein call karo",
        "Main travel kar raha hoon, baad mein call karo",
        "Abhi meeting mein hoon, baad mein call karo",
        "Tomorrow call karo please",
        "Main abhi driving kar raha hoon",
        "Weekend mein call karo",
        "Abhi convenient nahi hai",
        "Baad mein call kar lena",
        "Main abhi ghar par nahi hoon",
        "Next month call karo",
        "Abhi discuss nahi kar sakta",
        "Kal subah call karo",
        "Main abhi hospital mein hoon",
        "Evening mein call karo",
        "Abhi baat karne ka time nahi hai",
        "Next week available rahunga",
        "Main abhi family ke saath hoon",
        "Baad mein call kar lena please",
        "Abhi busy hoon, later call karo",
        "Tomorrow evening call karo",
        "Main abhi important work mein hoon",
        "Next week call kar lena"
    ],
    
    "unable_to_pay": [
        "Meri naukri chali gayi, paise nahi hain",
        "Main abhi kuch bhi pay nahi kar sakta",
        "Main financially struggling hoon",
        "Meri income nahi hai",
        "Paise nahi hain, kuch nahi de sakta",
        "Main jobless hoon, paise nahi hain",
        "Meri salary bandh ho gayi hai",
        "Main broke hoon, kuch nahi de sakta",
        "Mere paas paise nahi hain",
        "Main afford nahi kar sakta",
        "Meri financial condition theek nahi hai",
        "Main paise nahi de sakta abhi",
        "Meri savings khatam ho gayi",
        "Main unemployed hoon",
        "Mere paas funds nahi hain",
        "Main financially weak hoon",
        "Meri income source bandh ho gayi",
        "Main paise nahi de sakta",
        "Meri financial situation kharab hai",
        "Main broke hoon abhi",
        "Mere paas money nahi hai",
        "Main afford nahi kar sakta payment",
        "Meri job chali gayi hai",
        "Main financially unstable hoon",
        "Mere paas resources nahi hain",
        "Main paise nahi de sakta right now",
        "Meri financial crisis hai",
        "Main paise nahi de sakta abhi",
        "Mere paas funds available nahi hain",
        "Main financially unable hoon"
    ],
    
    "willing": [
        "Main pay karna chahta hoon lekin full amount nahi de sakta",
        "Kya main installments mein pay kar sakta hoon?",
        "Main pay karne ko ready hoon, payment options dikhao",
        "Main monthly pay kar sakta hoon, kya options hain?",
        "Main settle karna chahta hoon, kya hum plan bana sakte hain?",
        "Main EMI mein pay kar sakta hoon",
        "Payment plan de do please",
        "Main partial payment kar sakta hoon",
        "Kya main monthly installments de sakta hoon?",
        "Main pay karne ko willing hoon",
        "Payment options dikhao please",
        "Main monthly basis par pay kar sakta hoon",
        "Kya main thoda thoda pay kar sakta hoon?",
        "Main payment karne ko ready hoon",
        "EMI plan chahiye mujhe",
        "Main pay kar sakta hoon but installments mein",
        "Payment options kya hain?",
        "Main settle kar sakta hoon but plan chahiye",
        "Main monthly pay kar sakta hoon",
        "Kya main payment plan le sakta hoon?",
        "Main pay karne ko interested hoon",
        "Payment options batao please",
        "Main monthly EMI de sakta hoon",
        "Kya main payment plan choose kar sakta hoon?",
        "Main pay kar sakta hoon but monthly basis par",
        "Payment options dikhao",
        "Main settle kar sakta hoon installment mein",
        "Kya main payment plan select kar sakta hoon?",
        "Main pay karne ko ready hoon, options chahiye",
        "Payment plan ke liye ready hoon main"
    ],
    
    "unknown": [
        "Hi",
        "Yeh kaun hai?",
        "Samajh nahi aaya",
        "Aap kya keh rahe hain?",
        "Explain kar sakte hain?",
        "Hello",
        "Kya baat hai?",
        "Mujhe samajh nahi aaya",
        "Aap kya bol rahe hain?",
        "Kya matlab hai?",
        "Haan",
        "Nahi",
        "Theek hai",
        "Achha",
        "Ok",
        "Kya?",
        "Kaise?",
        "Kyun?",
        "Kahan?",
        "Kab?",
        "Kaun?",
        "Kya hua?",
        "Batao",
        "Suno",
        "Dekho",
        "Wait",
        "Ruko",
        "Thoda ruko",
        "Ek minute",
        "Just a moment"
    ]
}
